server:
  port: 80
  tomcat:
    max-connections: 10000
    max-threads: 10000
    max-http-post-size: 0
    protocol-header-https-value: http
  jetty:
    acceptors: 1000
  max-http-header-size: 2097152

mybatis:
  mapper-locations:
  - classpath:/mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  thymeleaf:
    encoding: utf-8
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.24.246.221:3306/myintroduction?useunicode=true
    username: root
    password: 369963
    tomcat:
      init-s-q-l: set names utf8mb4 collate utf8mb4_unicode_ci
  http:
    encoding:
      charset: utf-8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 30MB

swagger:
  enabled: true
  base-package: top.myideas.controller
logging:
  level:
    ROOT: ERROR
  file: /root/myintroduction.log

app:
  images: D:\\eclipse-workspace\\myIntroduction\\src\\main\\resources\\static\\upload\\


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
